# Site settings
title: Toh Yong Cheng
email: tohyongcheng@gmail.com
job_title: Software Engineer @ Skyscanner
description: > # this means to ignore newlines until "baseurl:"
  Personal ramblings of Toh Yong Cheng
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tohyongcheng.github.io" # the base hostname & protocol for your site
twitter_username: sebastiantoh
github_username:  tohyongcheng

# Build settings
markdown: kramdown
